echo Build all repos...

echo Building api-gateway...
docker build -t kokt0203/nest-api-gateway ../api-gateway

echo Building auth-server...
docker build -t kokt0203/nest-auth-svc ../auth-server

echo Building order-server...
docker build -t kokt0203/nest-order-svc ../order-server

echo Building product-server...
docker build -t kokt0203/nest-product-svc ../product-server

echo Remove unused images...
docker image prune -f

echo DONE!